### ISSUE TITLE
Issue with Redis to set up GetOutline Container

### ISSUE THREAD

**Issue by MetaBliss** [SimpleHomelab/Docker-Traefik#175]
Hi, I recently came across a company called GetOutline (www.getoutline.com) that has developed a "knowledge management" database type system similar to Notion, Roam Research, Obsidian. They made their solution available to be self-hosted as a docker container: outline/outline. However, there are quite a few dependencies for it (requires **Redis**, slack/google authentication, Amazon S3 database, Postgresql, etc.) 

1) As a general question, do you take requests to look into installing new containers like this? As your team does phenomenal guides, I'm sure a guide on this would be really beneficial for other folks who wish to use this container. I saw someone else who provided a guide but I'm still a beginner and some of his steps seemed a bit advanced. You may know how he installed it: https://blog.gurucomputing.com.au/deploying-outline-with-docker-and-caddy/

I had a few questions related to **Redis** if you don't mind. I think the problem I'm facing could affect others in other situations (beyond installing the GetOutline container so I think it'd still be helpful/relevant to others in other use cases).

The docker compose I was using has been provided below at the very bottom of this post. I am using a Synology NAS (DS 920+) with Docker installed. However, I am using the Portainer container management rather than command line (I am not so comfortable using CLI and I've had no issues being able to use the Portainer GUI thus far so I only use that). 

2) When I run my stack on Portainer using the Docker Compose, I get errors in the logs of the GetOutline container (which has **Redis** as a dependency). I keep getting the following error:

`Redis error: connect ECONNREFUSED 127.0.0.1:6377....Redis error: Reached the max retries per request limit (which is 20).
Refer to "maxRetriesPerRequest" option for details.. Shutting down now.,
Retrying redis connection: attempt 21.
at Socket.emit (events.js:315:20), at Object.onceWrapper (events.js:422:26), at Socket.EventEmitter.emit (domain.js:467:12), at TCP.<anonymous> (net.js:673:12),
error Command failed with exit code 1.,
at Socket.<anonymous> (/opt/outline/node_modules/ioredis/built/redis/event_handler.js:173:37)`

However, when I check the error logs of the Redis container, I'm seeing a different mesage in the Redis log below.
Would you be able to provide any insights as to what the problem could be?

`1:C 07 Jun 2021 21:56:21.640 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo, 1:C 07 Jun 2021 21:56:21.640 # Redis version=6.2.3, bits=64, commit=00000000, modified=0, pid=1, just started, 1:C 07 Jun 2021 21:56:21.640 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf, 1:M 07 Jun 2021 21:56:21.640 * monotonic clock: POSIX clock_gettime, 1:M 07 Jun 2021 21:56:21.641 * Running mode=standalone, port=6379., 1:M 07 Jun 2021 21:56:21.641 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128., 1:M 07 Jun 2021 21:56:21.641 # Server initialized, 1:M 07 Jun 2021 21:56:21.641 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect., 1:M 07 Jun 2021 21:56:21.641 * Loading RDB produced by version 6.2.3, 1:M 07 Jun 2021 21:56:21.641 * RDB age 3 seconds, 1:M 07 Jun 2021 21:56:21.641 * RDB memory usage when created 0.77 Mb, 1:M 07 Jun 2021 21:56:21.641 * DB loaded from disk: 0.000 seconds, 1:M 07 Jun 2021 21:56:21.641 * Ready to accept connections,`

For reference, my docker compose for installing GetOutline is below. I have built this using the guide from the link I put near the beginning of my post above. 

Thanks for any help you can provide!

![image](https://user-images.githubusercontent.com/84720384/121810421-d50ea200-cc2e-11eb-84ed-91d5d169566a.png)

**Comment by celi28** [comment]
Hello,
Your outline.env file contain :
```REDIS_URL=redis://localhost:6379```
which should be modified to 
```REDIS_URL=redis://outline_redis:6379``` in order to point to your redis container.

By default, outline redis container expose 6379 port.
